Weekly update of libShowRec. Just minor fixes.
Next working element: fix root compilation warning which appears for variable float types:
Error: *** Datamember EdbShowAlgE::eInANN: no size indication!
Error: *** Datamember EdbShowAlgE::eInANN: pointer to fundamental type (need manual intervention)
Error: *** Datamember EdbShowAlgE::eInfoANN: no size indication!
Error: *** Datamember EdbShowAlgE::eInfoANN: pointer to fundamental type (need manual intervention)




git-svn-id: http://emulsion.na.infn.it/svn/fedra/trunk@1465 96872706-0045-0410-9534-84be8447c86c